package dns

import (
	"fmt"
	"log/slog"
	"net"
	"os"
	"os/exec"
	"strings"

	"github.com/devakxhay/lighthouse/models"
)

type Manager struct {
	DnsmasqConf string
	DevMode     bool
	log         *slog.Logger
}

func NewManager(dnsmasqConf string, devMode bool, logger *slog.Logger) *Manager {
	return &Manager{
		DnsmasqConf: dnsmasqConf,
		DevMode:     devMode,
		log:         logger.With(slog.String("component", "dnsmasq")),
	}
}

// GetLocalIP returns the non-loopback local IPv4 address of the host.
func GetLocalIP() string {
	addrs, err := net.InterfaceAddrs()
	if err != nil {
		return "127.0.0.1"
	}
	for _, address := range addrs {
		if ipnet, ok := address.(*net.IPNet); ok && !ipnet.IP.IsLoopback() {
			if ipnet.IP.To4() != nil {
				return ipnet.IP.String()
			}
		}
	}
	return "127.0.0.1"
}

// Sync writes all apps domains to dnsmasq config and restarts the service.
func (m *Manager) Sync(apps []models.App) error {
	var lines []string
	lines = append(lines, "# Managed by Lighthouse", "# Do not edit this file manually", "")

	localIP := GetLocalIP()

	for _, app := range apps {
		if app.Domain != "" {
			lines = append(lines, fmt.Sprintf("address=/%s/%s", app.Domain, localIP))
		}
	}

	content := strings.Join(lines, "\n") + "\n"

	m.log.Debug("writing dnsmasq config", "path", m.DnsmasqConf)
	if err := os.WriteFile(m.DnsmasqConf, []byte(content), 0644); err != nil {
		return fmt.Errorf("write dnsmasq config: %w", err)
	}

	return m.Restart()
}

// Restart restarts the dnsmasq service using systemctl.
func (m *Manager) Restart() error {
	if m.DevMode {
		m.log.Debug("[DEV MODE] skipping: dnsmasq restart")
		return nil
	}

	cmd := exec.Command("sudo", "systemctl", "restart", "dnsmasq")
	out, err := cmd.CombinedOutput()
	if err != nil {
		m.log.Error("dnsmasq restart failed", "error", err.Error(), "output", string(out))
		return fmt.Errorf("restart dnsmasq: %w: %s", err, string(out))
	}

	m.log.Info("dnsmasq restarted successfully")
	return nil
}
